version: 2.1

executors:
  dotnet:
    parameters:
      image_tag: { type: string, default: 6.0-alpine }
    docker:
      - image: mcr.microsoft.com/dotnet/sdk:<< parameters.image_tag >>
    working_directory: /project
    environment:
      NUGET_PACKAGES: /project/packages

jobs:
  build:
    executor: dotnet
    steps:
      - checkout
      - run:
          name: print dotnet information
          command: dotnet --info
      - run:
          name: build
          command: dotnet build -c Release --no-incremental -v normal
      - persist_to_workspace:
          root: .
          paths:
            - ./*

  unittest:
    parameters:
      image_tag: { type: string }
      target_framework: { type: string }
    executor:
      name: dotnet
      image_tag: << parameters.image_tag >>
    steps:
      - attach_workspace:
          at: .
      - run:
          name: run test
          command: >-
            dotnet test -c Release --no-build -v normal
            --framework << parameters.target_framework >>
            --results-directory ./TestResults
            --logger "console;verbosity=detailed"
            --logger "trx;LogFileName=TestResult.xml"
            < /dev/null
      - store_artifacts:
          path: ./TestResults/TestResult.xml
          destination: TestResult_<< parameters.target_framework >>.xml

  pack:
    executor: dotnet
    steps:
      - attach_workspace:
          at: .
      - run:
          name: create package
          command: >-
            dotnet pack -c Release --no-build -v normal ParsecSharp
            --output ./nuget
            -p:RepositoryBranch=${CIRCLE_BRANCH},RepositoryCommit=${CIRCLE_SHA1}
      - store_artifacts:
          path: ./nuget
      - persist_to_workspace:
          root: ./nuget
          paths:
            - ./ParsecSharp.*.symbols.nupkg

  push:
    executor: dotnet
    steps:
      - attach_workspace:
          at: .
      - run:
          name: push to NuGet gallery
          command: >-
            dotnet nuget push ./ParsecSharp.*.symbols.nupkg
            --source https://www.nuget.org --api-key ${NUGET_APIKEY}

workflows:
  workflow:
    jobs:
      - build:
          filters: &default_filter
            branches:
              only:
                - master
                - dev
            tags:
              only: /^v\d+\.\d+\.\d+(-.+)?$/

      - unittest:
          name: unittest6.0
          image_tag: 6.0-alpine
          target_framework: net6.0
          requires:
            - build
          filters: *default_filter

      - unittest:
          name: unittest5.0
          image_tag: 5.0-alpine
          target_framework: net5.0
          requires:
            - build
          filters: *default_filter

      - unittest:
          name: unittest3.1
          image_tag: 3.1-alpine
          target_framework: netcoreapp3.1
          requires:
            - build
          filters: *default_filter

      - pack:
          requires:
            - build
          filters: *default_filter

      - push:
          context: nuget-publish
          requires:
            - pack
            - unittest6.0
            - unittest5.0
            - unittest3.1
          filters:
            <<: *default_filter
            branches:
              ignore: /.*/
