version: 2.1

executors:
  dotnet:
    parameters:
      sdk_version: { type: string, default: "10.0-preview" }
    docker:
      - image: mcr.microsoft.com/dotnet/nightly/sdk:<< parameters.sdk_version >>-alpine
    working_directory: /_
    environment:
      NUGET_PACKAGES: /_/packages

jobs:
  build:
    executor: dotnet
    steps:
      - checkout
      - run:
          name: print dotnet information
          command: dotnet --info
      - run:
          name: build
          command: dotnet build -c Release --no-incremental -v normal
      - persist_to_workspace:
          root: .
          paths:
            - ./*

  unittest:
    parameters:
      sdk_version: { type: string }
      target_framework: { type: string }
    executor:
      name: dotnet
      sdk_version: << parameters.sdk_version >>
    steps:
      - attach_workspace:
          at: .
      - run:
          name: run test
          command: >-
            dotnet test UnitTest.ParsecSharp
            -c Release --no-build -v normal
            --framework << parameters.target_framework >>
            --results-directory ./TestResults
            --logger "console;verbosity=detailed"
            --logger "trx;LogFileName=TestResult.xml"
            < /dev/null
      - store_artifacts:
          path: ./TestResults/TestResult.xml
          destination: TestResult_<< parameters.target_framework >>.xml

  pack:
    executor: dotnet
    steps:
      - attach_workspace:
          at: .
      - run:
          name: create package
          command: >-
            dotnet pack -c Release --no-build -v normal ParsecSharp
            --output ./nuget
            -p:RepositoryBranch=${CIRCLE_BRANCH},RepositoryCommit=${CIRCLE_SHA1}
      - store_artifacts:
          path: ./nuget
      - persist_to_workspace:
          root: ./nuget
          paths:
            - ./ParsecSharp.*.nupkg

  push:
    executor: dotnet
    steps:
      - attach_workspace:
          at: .
      - run:
          name: push to NuGet gallery
          command: >-
            dotnet nuget push ./ParsecSharp.*.nupkg
            --source https://www.nuget.org --api-key ${NUGET_APIKEY}

workflows:
  workflow:
    jobs:
      - build:
          filters: &default_filter
            tags:
              only: /^v\d+\.\d+\.\d+(-.+)?$/

      - unittest:
          name: unittest10.0
          sdk_version: "10.0-preview"
          target_framework: net10.0
          requires:
            - build
          filters: *default_filter

      - unittest:
          name: unittest9.0
          sdk_version: "9.0"
          target_framework: net9.0
          requires:
            - build
          filters: *default_filter

      - unittest:
          name: unittest8.0
          sdk_version: "8.0"
          target_framework: net8.0
          requires:
            - build
          filters: *default_filter

      - unittest:
          name: unittest6.0
          sdk_version: "6.0"
          target_framework: net6.0
          requires:
            - build
          filters: *default_filter

      - pack:
          requires:
            - build
          filters: *default_filter

      - push:
          context: nuget-publish
          requires:
            - pack
            - unittest10.0
            - unittest9.0
            - unittest8.0
            - unittest6.0
          filters:
            <<: *default_filter
            branches:
              ignore: /.*/
